case: "burn"
model:
  name: "Prithvi_Global_burn"
  n_channel: 6
  n_class: 2
  encoder_embed_dim: 1024
  dec_embed_dim: 512
  dropout_rate: 0.2

dataset_used: 0.1

device_name: "cuda"
wandb_project: "HLS-burn-finetune-10prcnt-prithviGlobal"

n_iteration: 10

prithvi_model_new_weight: "/home/sagemaker-user/prithvi-global-finetuning/code/models/checkpoint.pt"

training:
  batch_size: 8
  learning_rate: 0.0001
  shuffle: True
  relative_path: 'training'

validation:
  batch_size: 16
  shuffle: False
  relative_path: 'validation'

data:
  n_frame: 1
  data_dir_input: "/home/sagemaker-user/prithvi-global-finetuning/code/datasets/"
  data_dir_mask: "/home/sagemaker-user/prithvi-global-finetuning/code/datasets/"
  means: [
        0.033349706741586264,
        0.05701185520536176,
        0.05889748132001316,
        0.2323245113436119,
        0.1972854853760658,
        0.11944914225186566
    ]
  stds: [
        0.02269135568823774,
        0.026807560223070237,
        0.04004109844362779,
        0.07791732423672691,
        0.08708738838140137,
        0.07241979477437814
    ]
  input_size: [1,224,224]
  patch_size: [1,16,16]

Loss: "CrossEntropyLoss"

class_weights:  [0.11, 0.88]

ignore_index: -1

logging:

  checkpoint_dir: "/home/sagemaker-user/prithvi-global-finetuning/code/models/"

segment_input_path: "/home/sagemaker-user/prithvi-global-finetuning/code/datasets/validation/subsetted_512x512_HLS.S30.T16SFD.2019100.v1.4_merged.tif"

predicted_mask_dir: "./segment_out_prithvi_burn"


prithvi_backbone:
  depth: 24
  num_heads: 16
  mlp_ratio: 4

check_output: 2

class_index_correction: 0

colormap: [
  [0, 0, 0],
  [255, 255, 255],
]
