model:
  name: "UNet_Prithvi_New"
  n_channel: 6
  n_class: 2
  embed_dim: 1024
  dropout_rate: 0.5

device_name: "cuda"
wandb_project: "HLS-floodV2-finetune-unet_new-prithvi100M"

n_iteration: 125

prithvi_model_new_weight: "/rhome/rghosal/Rinki/rinki-hls-foundation-os/Prithvi_global.pt"
prithvi_model_old_config: "/rhome/rghosal/Rinki/rinki-hls-foundation-os/prithvi_merra/Prithvi_100M/Prithvi_100_config.yaml"

training:
  train_batch_size: 16
  learning_rate: 6e-5
  shuffle: True

  optimizer:
    name: "AdamW"
    params:
      lr: 6e-5
       

  scheduler:
    name: "ReduceLROnPlateau"



validation:
  val_batch_size: 16
  shuffle: False

testing:
  test_batch_size: 16
  shuffle: False


data:
  n_frame: 1
  data_dir_input: "/rhome/rghosal/flood_map/v1.1/data/flood_events/HandLabeled/S2Hand"
  data_dir_mask: "/rhome/rghosal/flood_map/v1.1/data/flood_events/HandLabeled/LabelHand"
  train_annot: "/rhome/rghosal/flood_map/v1.1/splits/flood_handlabeled/flood_train_data.csv"
  val_annot: "/rhome/rghosal/flood_map/v1.1/splits/flood_handlabeled/flood_valid_data.csv"
  test_annot: "/rhome/rghosal/flood_map/v1.1/splits/flood_handlabeled/flood_test_data.csv"
  input_size: [1,224, 224]
  means: [0.14245495,0.13921481,0.12434631,0.31420089,0.20743526, 0.12046503]
  stds: [0.04036231, 0.04186983, 0.05267646,0.0822221,0.06834774,0.05294205]
  
Loss: "CrossEntropyLoss"

class_weights: [0.3, 0.7]
ignore_index: -1

logging:
  checkpoint_dir: "/rhome/rghosal/Rinki/rinki-hls-foundation-os/flood_v2_checkpoint/checkpoint_flood_new_sample2.pth" 

segment_input_path: "/rhome/rghosal/flood_map/v1.1/data/flood_events/HandLabeled/S2Hand/USA_1010394_S2Hand.tif"

predicted_mask_dir: "./segment_out_new_flood"