case: "flood"
check_output: 2

class_index_correction: 0

colormap: [
  [0, 0, 0],
  [255, 255, 255],
]

model:
  name: "Prithvi_Global_flood"
  n_channel: 6
  n_class: 2
  encoder_embed_dim: 1024
  dec_embed_dim: 512
  dropout_rate: 0.2

dataset_used: 0.1

device_name: "cuda"
wandb_project: "HLS-flood-finetune-10prcnt-prithviGlobal"

n_iteration: 10

prithvi_model_new_weight: "/home/sagemaker-user/prithvi-global-finetuning/code/models/prithvi_global_v1.pt"

training:
  batch_size: 8
  learning_rate: 0.0001
  shuffle: True
  relative_path: ''
  annot: 'flood_train_data.csv'

validation:
  batch_size: 16
  shuffle: False
  relative_path: ''
  annot: 'flood_valid_data.csv'

test:
  batch_size: 16
  shuffle: False
  relative_path: ''
  annot: 'flood_test_data.csv'

data:
  n_frame: 1
  data_dir_input: "/home/sagemaker-user/prithvi-global-finetuning/code/datasets/flood_events/S2Hand"
  data_dir_input: "/home/sagemaker-user/prithvi-global-finetuning/code/datasets/flood_events/LabelHand"
  means: [0.14245495, 0.13921481, 0.12434631, 0.31420089, 0.20743526, 0.12046503]
  stds: [0.04036231, 0.04186983, 0.05267646, 0.0822221, 0.06834774, 0.05294205]
  input_size: [1,224,224]
  patch_size: [1,16,16]

Loss: "CrossEntropyLoss"

class_weights:  [0.3, 0.7]

ignore_index: -1

logging:

  checkpoint_dir: "/rhome/rghosal/Rinki/rinki-hls-foundation-os/final_checkpoint"

segment_input_path: "/rhome/rghosal/flood_map/v1.1/data/flood_events/HandLabeled/S2Hand/USA_1010394_S2Hand.tif"


predicted_mask_dir: "./segment_out_prithvi_flood"

prithvi_backbone:
  depth: 24
  num_heads: 16
  mlp_ratio: 4