model:
  name: "Prithvi_Global_burn"
  n_channel: 6
  n_class: 5
  embed_dim: 1024
  dec_embed_dim: 512
  dropout_rate: 0.2

device_name: "cuda"
wandb_project: "HLS-burn-intensity-finetune-prithviGlobal"

n_iteration: 125

prithvi_model_new_weight: "/rhome/rghosal/Rinki/rinki-hls-foundation-os/Prithvi_global.pt"

training:
  train_batch_size: 8
  learning_rate: 0.0001
  shuffle: False

  optimizer:
    name: "AdamW"
    params:
      lr: 0.0001
       

  scheduler:
    name: "StepLR"
    params:
      step_size: 10
      gamma: 0.9


validation:
  val_batch_size: 8
  shuffle: False


data:
  n_frame: 1
  data_dir: ["/rgroup/aifm/akumar/Burn_Scar/Burn_Scar_cropped_v2/pre",
            "/rgroup/aifm/akumar/Burn_Scar/Burn_Scar_cropped_v2/current",
            "/rgroup/aifm/akumar/Burn_Scar/Burn_Scar_cropped_v2/post"]
  annot_dir: "."
  means: [[1027.0479, 1230.4219, 1270.1404, 1895.1371, 1366.3008, 2467.9395],
          [1027.0479, 1230.4219, 1270.1404, 1895.1371, 1366.3008, 2467.9395],
          [1027.0479, 1230.4219, 1270.1404, 1895.1371, 1366.3008, 2467.9395]]
  stds: [[1735.9897, 1725.6100, 1687.5278, 1252.5571, 1122.0760, 1522.4668],
          [1735.9897, 1725.6100, 1687.5278, 1252.5571, 1122.0760, 1522.4668],
          [1735.9897, 1725.6100, 1687.5278, 1252.5571, 1122.0760, 1522.4668]]
  input_size: [3,224,224]
  patch_size: [1,16,16]
  
Loss: "CrossEntropyLoss"

class_weights: [.018, 0.14, 0.076, 0.11, 0.65]

ignore_index: -1

logging:
  checkpoint_dir: "/rhome/rghosal/Rinki/rinki-hls-foundation-os/prithvi_burn_intensity_checkpoint/checkpoint_burn_intensity_prithvi.pth" 

segment_input_path: "/rgroup/aifm/akumar/Burn_Scar/Burn_Scar_cropped/HLS_red_apple_0224_0224.tiff"
predicted_mask_dir: "./segment_out_prithvi_burn"